# Generated by Django 4.0.5 on 2022-07-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uslovie',
            name='begin',
            field=models.CharField(help_text='Введите временной период начала', max_length=1000, null=True, verbose_name='Декады'),
        ),
        migrations.AddField(
            model_name='uslovie',
            name='ending',
            field=models.CharField(help_text='Введите массовый временной период', max_length=1000, null=True, verbose_name='Декады'),
        ),
    ]
