# Generated by Django 4.0.5 on 2022-07-13 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_uslovie_begin_uslovie_ending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='culture',
            name='uslovie',
        ),
        migrations.AddField(
            model_name='vozdeistvie',
            name='uslovie',
            field=models.ForeignKey(help_text='Выберите нужные условия', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.uslovie', verbose_name='Условия'),
        ),
        migrations.AlterField(
            model_name='uslovie',
            name='set',
            field=models.BooleanField(help_text='Разчитать сумму эффективных температур?', verbose_name='Сумма эффективных температур'),
        ),
        migrations.AlterField(
            model_name='uslovie',
            name='verh_porog',
            field=models.FloatField(help_text='Введите верхний порог развития', verbose_name='Верхний порог развития'),
        ),
    ]
