# Generated by Django 4.0.5 on 2022-07-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_culture_uslovie_vozdeistvie_uslovie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vozdeistvie',
            name='uslovie',
        ),
        migrations.RemoveField(
            model_name='culture',
            name='vozdeistvie',
        ),
        migrations.AddField(
            model_name='culture',
            name='vozdeistvie',
            field=models.ManyToManyField(help_text='Выберите воздействие', null=True, to='catalog.vozdeistvie', verbose_name='Воздействие'),
        ),
        migrations.AlterField(
            model_name='vozdeistvie',
            name='describe',
            field=models.CharField(help_text='Введите описание воздействия', max_length=100, verbose_name='Описание воздействия'),
        ),
        migrations.AlterField(
            model_name='vozdeistvie',
            name='tip',
            field=models.BooleanField(help_text='Отметьте галочку, если воздействие - вредитель', verbose_name='Тип воздействия'),
        ),
        migrations.DeleteModel(
            name='Uslovie',
        ),
    ]
