# Generated by Django 4.1 on 2023-04-27 13:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_vozdeistvie_uslovie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punct', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
            ],
        ),
        migrations.AlterField(
            model_name='culture',
            name='vozdeistvie',
            field=models.ManyToManyField(help_text='Выберите воздействие', to='catalog.vozdeistvie', verbose_name='Воздействие'),
        ),
        migrations.AlterField(
            model_name='vozdeistvie',
            name='describe',
            field=models.TextField(help_text='Введите описание воздействия', verbose_name='Описание воздействия'),
        ),
        migrations.AlterField(
            model_name='vozdeistvie',
            name='name',
            field=models.CharField(default='', help_text='Введите причину воздействия', max_length=200, verbose_name='Воздействие'),
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.date.today)),
                ('min_t', models.FloatField()),
                ('max_t', models.FloatField()),
                ('avg_t', models.FloatField(blank=True, null=True)),
                ('avg_v', models.FloatField()),
                ('rain', models.FloatField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperatures', to='catalog.city')),
            ],
        ),
        migrations.AddField(
            model_name='vozdeistvie',
            name='fotos',
            field=models.ManyToManyField(blank=True, to='catalog.foto', verbose_name='Фотографии'),
        ),
    ]
