# Generated by Django 4.1 on 2023-04-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_city_foto_alter_culture_vozdeistvie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temperature',
            name='avg_v',
        ),
        migrations.AddField(
            model_name='temperature',
            name='avg_vl',
            field=models.FloatField(blank=True, null=True, verbose_name='Влажносить воздуха'),
        ),
        migrations.AddField(
            model_name='temperature',
            name='soln_rad',
            field=models.FloatField(blank=True, null=True, verbose_name='Солнечная радиация'),
        ),
        migrations.AddField(
            model_name='temperature',
            name='t_sol',
            field=models.FloatField(blank=True, null=True, verbose_name='температура почвы'),
        ),
        migrations.AddField(
            model_name='temperature',
            name='vl_list',
            field=models.FloatField(blank=True, null=True, verbose_name='Влажность листа'),
        ),
        migrations.AddField(
            model_name='temperature',
            name='vl_sol',
            field=models.FloatField(blank=True, null=True, verbose_name='Влажность почвы'),
        ),
        migrations.AddField(
            model_name='vozdeistvie',
            name='describe2',
            field=models.TextField(blank=True, help_text='Введите повреждения от воздействия', null=True, verbose_name='Описание Повреждений'),
        ),
        migrations.AddField(
            model_name='vozdeistvie',
            name='describe3',
            field=models.TextField(blank=True, help_text='Введите методы борьбы', null=True, verbose_name='Описание методов'),
        ),
        migrations.AddField(
            model_name='vozdeistvie',
            name='describe_1',
            field=models.TextField(blank=True, help_text='Введите Стадии развития', null=True, verbose_name='Описание стадий'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='avg_t',
            field=models.FloatField(blank=True, null=True, verbose_name='средняя температура'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='max_t',
            field=models.FloatField(blank=True, null=True, verbose_name='максимальная температура'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='min_t',
            field=models.FloatField(blank=True, null=True, verbose_name='минимальная температура'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='rain',
            field=models.FloatField(blank=True, null=True, verbose_name='осадки мм'),
        ),
        migrations.AlterField(
            model_name='vozdeistvie',
            name='describe',
            field=models.TextField(blank=True, help_text='Введите описание воздействия', null=True, verbose_name='Описание воздействия'),
        ),
        migrations.AlterField(
            model_name='vozdeistvie',
            name='fotos',
            field=models.ManyToManyField(blank=True, null=True, to='catalog.foto', verbose_name='Фотографии'),
        ),
    ]
